<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/8 0008
 * Time: 上午 10:13
 */

namespace backend\controllers;


use backend\models\Liuyanban;
use yii\web\Controller;

class LiuyanbanController extends Controller
{
    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
        $session = \Yii::$app->session;
        if (empty($session['userInfo'])) {
            return $this->redirect('index.php?r=login/index');
        }
    }

    public function actionIndex() {
        $list = Liuyanban::find()->all();
        return $this->render('index', [
            'list' =>$list,
        ]);
    }

    public function actionAddsave() {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $session = \Yii::$app->session;
        $user = new Liuyanban();
        $user->username = $session->get('userInfo')['username'];
        $user->contents = \Yii::$app->request->post('contents');
        $user->create_time = time();
        $user->update_time = time();
        $user->save();
        $result = Liuyanban::findOne(['create_time' => $user->create_time]);
        return $result;
    }

    public function actionDelete() {
        $id = \Yii::$app->request->get('id');
        $info = empty($id) ? null : Liuyanban::find()->where(['id' => $id])->one();
        if ($info) {
            if ($info->delete()) {
                $this->redirect(['index']);
            } else {
                echo '删除失败';
            }
        } else {
            echo '要删除的数据不存在';
        }
    }
}